
"""
Add your CosmosDB NoSQL database schema in this file

For example:

type User @model {
  id: ID
  username: String
  score: Int
}

"""

type User @model {
  id: ID
  username: String
  score: Int
}